"""ajout_tables_cameras_et_comptage

Révision : 22db771a8f66
Révise : e370b393b23b
Créée le : 2026-09-24 17:56:42.610682+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Identifiants de révision utilisés par Alembic.
revision: str = '22db771a8f66'
down_revision: str | Sequence[str] | None = 'e370b393b23b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('sn', sa.String(length=64), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('emplacement', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=30), nullable=True),
    sa.Column('modele', sa.String(length=50), nullable=False),
    sa.Column('version_logiciel', sa.String(length=50), nullable=True),
    sa.Column('role_reseau', sa.String(length=20), nullable=False),
    sa.Column('statut_en_ligne', sa.Boolean(), nullable=False),
    sa.Column('dernier_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_index(op.f('ix_cameras_sn'), 'cameras', ['sn'], unique=True)
    op.create_table('camera_heartbeats',
    sa.Column('camera_id', sa.Uuid(), nullable=True),
    sa.Column('camera_sn', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.BigInteger(), nullable=False),
    sa.Column('etat', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('donnees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_camera_heartbeats_camera_id_cameras'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_heartbeats'))
    )
    op.create_index(op.f('ix_camera_heartbeats_camera_id'), 'camera_heartbeats', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_heartbeats_camera_sn'), 'camera_heartbeats', ['camera_sn'], unique=False)
    op.create_index(op.f('ix_camera_heartbeats_created_at'), 'camera_heartbeats', ['created_at'], unique=False)
    op.create_table('passages_comptage',
    sa.Column('camera_id', sa.Uuid(), nullable=True),
    sa.Column('master_sn', sa.String(length=64), nullable=False),
    sa.Column('batch_date', sa.String(length=10), nullable=False),
    sa.Column('stat_basis', sa.String(length=10), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.Column('interval_s', sa.Integer(), nullable=False),
    sa.Column('start_ts_s', sa.BigInteger(), nullable=False),
    sa.Column('end_ts_s', sa.BigInteger(), nullable=False),
    sa.Column('horodatage_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entrees', sa.Integer(), nullable=False),
    sa.Column('sorties', sa.Integer(), nullable=False),
    sa.Column('passants', sa.Integer(), nullable=False),
    sa.Column('demi_tours', sa.Integer(), nullable=False),
    sa.Column('visiteurs_uniques', sa.Integer(), nullable=False),
    sa.Column('visiteurs_recidives', sa.Integer(), nullable=False),
    sa.Column('personnel_exclu', sa.Integer(), nullable=False),
    sa.Column('duree_sejour_moyenne_sec', sa.Integer(), nullable=False),
    sa.Column('repartition_age_genre', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repartition_taille', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repartition_sejour', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('donnees_brutes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_passages_comptage_camera_id_cameras'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passages_comptage')),
    sa.UniqueConstraint('master_sn', 'batch_date', 'start_ts_s', name='uq_passage_sn_date_debut')
    )
    op.create_index(op.f('ix_passages_comptage_batch_date'), 'passages_comptage', ['batch_date'], unique=False)
    op.create_index(op.f('ix_passages_comptage_camera_id'), 'passages_comptage', ['camera_id'], unique=False)
    op.create_index(op.f('ix_passages_comptage_created_at'), 'passages_comptage', ['created_at'], unique=False)
    op.create_index(op.f('ix_passages_comptage_horodatage_debut'), 'passages_comptage', ['horodatage_debut'], unique=False)
    op.create_index(op.f('ix_passages_comptage_master_sn'), 'passages_comptage', ['master_sn'], unique=False)
    op.create_index(op.f('ix_passages_comptage_start_ts_s'), 'passages_comptage', ['start_ts_s'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passages_comptage_start_ts_s'), table_name='passages_comptage')
    op.drop_index(op.f('ix_passages_comptage_master_sn'), table_name='passages_comptage')
    op.drop_index(op.f('ix_passages_comptage_horodatage_debut'), table_name='passages_comptage')
    op.drop_index(op.f('ix_passages_comptage_created_at'), table_name='passages_comptage')
    op.drop_index(op.f('ix_passages_comptage_camera_id'), table_name='passages_comptage')
    op.drop_index(op.f('ix_passages_comptage_batch_date'), table_name='passages_comptage')
    op.drop_table('passages_comptage')
    op.drop_index(op.f('ix_camera_heartbeats_created_at'), table_name='camera_heartbeats')
    op.drop_index(op.f('ix_camera_heartbeats_camera_sn'), table_name='camera_heartbeats')
    op.drop_index(op.f('ix_camera_heartbeats_camera_id'), table_name='camera_heartbeats')
    op.drop_table('camera_heartbeats')
    op.drop_index(op.f('ix_cameras_sn'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
