"""initiale

Révision : e370b393b23b
Révise : 
Créée le : 2026-09-18 01:27:08.364897+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Identifiants de révision utilisés par Alembic.
revision: str = 'e370b393b23b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jetons_revoques',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_jetons_revoques'))
    )
    op.create_index(op.f('ix_jetons_revoques_expire_le'), 'jetons_revoques', ['expire_le'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('nom_complet', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'UTILISATEUR', name='role_utilisateur', native_enum=False, length=20), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=False),
    sa.Column('otp_secret_chiffre', sa.String(length=255), nullable=True),
    sa.Column('otp_active', sa.Boolean(), nullable=False),
    sa.Column('tentatives_echouees', sa.Integer(), nullable=False),
    sa.Column('verrouille_jusqua', sa.DateTime(timezone=True), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utilisateurs'))
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('historique',
    sa.Column('utilisateur_id', sa.Uuid(), nullable=True),
    sa.Column('utilisateur_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Enum('CREATION', 'MODIFICATION', 'SUPPRESSION', 'CONNEXION', 'DECONNEXION', 'ECHEC_CONNEXION', 'VERROUILLAGE', 'INSCRIPTION', 'OTP_ACTIVATION', 'OTP_DESACTIVATION', 'DEMANDE_REINITIALISATION_MOT_DE_PASSE', 'REINITIALISATION_MOT_DE_PASSE', 'CHANGEMENT_MOT_DE_PASSE', name='action_historique', native_enum=False, length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('objet_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('donnees_avant', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('donnees_apres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('adresse_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], name=op.f('fk_historique_utilisateur_id_utilisateurs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historique'))
    )
    op.create_index(op.f('ix_historique_action'), 'historique', ['action'], unique=False)
    op.create_index(op.f('ix_historique_created_at'), 'historique', ['created_at'], unique=False)
    op.create_index(op.f('ix_historique_module'), 'historique', ['module'], unique=False)
    op.create_index(op.f('ix_historique_utilisateur_email'), 'historique', ['utilisateur_email'], unique=False)
    op.create_index(op.f('ix_historique_utilisateur_id'), 'historique', ['utilisateur_id'], unique=False)
    op.create_table('jetons_reinitialisation',
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('jeton_hash', sa.String(length=64), nullable=False),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utilise_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], name=op.f('fk_jetons_reinitialisation_utilisateur_id_utilisateurs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jetons_reinitialisation'))
    )
    op.create_index(op.f('ix_jetons_reinitialisation_jeton_hash'), 'jetons_reinitialisation', ['jeton_hash'], unique=True)
    op.create_index(op.f('ix_jetons_reinitialisation_utilisateur_id'), 'jetons_reinitialisation', ['utilisateur_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jetons_reinitialisation_utilisateur_id'), table_name='jetons_reinitialisation')
    op.drop_index(op.f('ix_jetons_reinitialisation_jeton_hash'), table_name='jetons_reinitialisation')
    op.drop_table('jetons_reinitialisation')
    op.drop_index(op.f('ix_historique_utilisateur_id'), table_name='historique')
    op.drop_index(op.f('ix_historique_utilisateur_email'), table_name='historique')
    op.drop_index(op.f('ix_historique_module'), table_name='historique')
    op.drop_index(op.f('ix_historique_created_at'), table_name='historique')
    op.drop_index(op.f('ix_historique_action'), table_name='historique')
    op.drop_table('historique')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_jetons_revoques_expire_le'), table_name='jetons_revoques')
    op.drop_table('jetons_revoques')
    # ### end Alembic commands ###
